import { GameItem, ProductSKU, PaymentChannel, SavedGameAccount, VoucherCoupon, StreamerReferral, ExclusivePartnerConfig } from "./types";
import { calculateMLProductSKUs } from "./pricing-calculator";

export const FEATURED_PROMOS = [
  {
    id: "promo-1",
    title: "Event Double 11 Mobile Legends",
    subtitle: "Bonus 500+ Diamond & Skin Epic Garansi Instan 3 Detik!",
    tag: "EVENT SPESIAL",
    badge: "Diskon 25%",
    gameSlug: "mobile-legends",
    bgGradient: "from-blue-900 via-indigo-950 to-slate-900",
    image: "/images/promos/promo-mlbb.jpg",
  },
  {
    id: "promo-2",
    title: "Free Fire Booyah Pass Season Terbaru",
    subtitle: "Top up 140 Diamonds Instan Masuk Otomatis via QRIS!",
    tag: "POPULER",
    badge: "Termurah",
    gameSlug: "free-fire",
    bgGradient: "from-amber-950 via-red-950 to-slate-900",
    image: "/images/promos/promo-ff.jpg",
  },
  {
    id: "promo-3",
    title: "Genshin Impact Blessing of Welkin Moon",
    subtitle: "Hanya Rp 68.500 via QRIS Otomatis & Terverifikasi!",
    tag: "BEST SELLER",
    badge: "Hemat 15%",
    gameSlug: "genshin-impact",
    bgGradient: "from-cyan-950 via-slate-900 to-blue-950",
    image: "/images/promos/promo-genshin.jpg",
  },
  {
    id: "promo-4",
    title: "Valorant Points (VP) Night Market",
    subtitle: "Diskon Bundle Skin Senjata & Battle Pass Terlengkap!",
    tag: "PROMO VP",
    badge: "Cashback 10%",
    gameSlug: "valorant",
    bgGradient: "from-slate-900 via-red-950 to-slate-950",
    image: "/images/games/valorant.svg",
  },
];

export const GAME_LIST: GameItem[] = [
  {
    id: "mlbb",
    slug: "mobile-legends",
    name: "Mobile Legends: Bang Bang",
    publisher: "Moonton",
    category: "game-mobile",
    thumbnail: "/images/games/mobile-legends.png",
    banner: "/images/promos/promo-mlbb.jpg",
    hasZoneId: true,
    zoneIdLabel: "Zone ID",
    zoneIdPlaceholder: "cth. 2001",
    userIdLabel: "User ID",
    userIdPlaceholder: "cth. 12345678",
    guideImage: "Format: 12345678 (2001) - Temukan di profil game MLBB kamu.",
    isPopular: true,
    tag: "HOT",
  },
  {
    id: "ff",
    slug: "free-fire",
    name: "Garena Free Fire",
    publisher: "Garena",
    category: "game-mobile",
    thumbnail: "/images/games/free-fire.png",
    banner: "/images/promos/promo-ff.jpg",
    hasZoneId: false,
    userIdLabel: "Player ID",
    userIdPlaceholder: "cth. 892348123",
    guideImage: "Cek Player ID di bawah nama karakter kamu di menu utama.",
    isPopular: true,
    tag: "HOT",
  },
  {
    id: "genshin",
    slug: "genshin-impact",
    name: "Genshin Impact",
    publisher: "HoYoverse",
    category: "game-mobile",
    thumbnail: "/images/games/genshin-impact.png",
    banner: "/images/promos/promo-genshin.jpg",
    hasZoneId: true,
    zoneIdLabel: "Pilih Server",
    zoneIdPlaceholder: "Asia / America / Europe / TW",
    userIdLabel: "UID Akun",
    userIdPlaceholder: "cth. 800123456",
    isPopular: true,
    tag: "PROMO",
  },
  {
    id: "pubgm",
    slug: "pubg-mobile",
    name: "PUBG Mobile",
    publisher: "Level Infinite",
    category: "game-mobile",
    thumbnail: "/images/games/pubg-mobile.png",
    banner: "/images/games/pubg-mobile.png",
    hasZoneId: false,
    userIdLabel: "User ID (Character ID)",
    userIdPlaceholder: "cth. 512398412",
    isPopular: true,
    tag: "HOT",
  },
  {
    id: "valorant",
    slug: "valorant",
    name: "Valorant",
    publisher: "Riot Games",
    category: "game-pc",
    thumbnail: "/images/games/valorant.svg",
    banner: "/images/games/valorant.svg",
    hasZoneId: false,
    userIdLabel: "Riot ID #Tagline",
    userIdPlaceholder: "cth. TenZ#NA1",
    isPopular: true,
    tag: "EVENT",
  },
  {
    id: "hok",
    slug: "honor-of-kings",
    name: "Honor of Kings",
    publisher: "Level Infinite",
    category: "game-mobile",
    thumbnail: "/images/games/honor-of-kings.png",
    banner: "/images/games/honor-of-kings.png",
    hasZoneId: false,
    userIdLabel: "User ID",
    userIdPlaceholder: "cth. 12948512",
    isPopular: true,
    tag: "NEW",
  },
  {
    id: "roblox",
    slug: "roblox",
    name: "Roblox",
    publisher: "Roblox Corp",
    category: "game-mobile",
    thumbnail: "/images/games/roblox.png",
    banner: "/images/games/roblox.png",
    hasZoneId: false,
    userIdLabel: "Username Roblox",
    userIdPlaceholder: "cth. Builderman",
    isPopular: false,
  },
  {
    id: "steam",
    slug: "steam-wallet",
    name: "Steam Wallet IDR",
    publisher: "Valve",
    category: "voucher",
    thumbnail: "/images/games/steam-wallet.svg",
    banner: "/images/games/steam-wallet.svg",
    hasZoneId: false,
    userIdLabel: "Nomor WhatsApp",
    userIdPlaceholder: "cth. 081234567890 (Kode dikirim via WA)",
    isPopular: false,
  },
  {
    id: "pln",
    slug: "pln-token",
    name: "Token Listrik PLN",
    publisher: "PLN Indonesia",
    category: "pulsa-ppob",
    thumbnail: "/images/games/pln-token.png",
    banner: "/images/games/pln-token.png",
    hasZoneId: false,
    userIdLabel: "Nomor Meter / ID Pelanggan",
    userIdPlaceholder: "cth. 14234567890",
    isPopular: false,
  },
  {
    id: "pulsa-tsel",
    slug: "pulsa-telkomsel",
    name: "Pulsa & Kuota Telkomsel",
    publisher: "Telkomsel",
    category: "pulsa-ppob",
    thumbnail: "/images/games/pulsa-telkomsel.svg",
    banner: "/images/games/pulsa-telkomsel.svg",
    hasZoneId: false,
    userIdLabel: "Nomor Telkomsel",
    userIdPlaceholder: "cth. 081289123456",
    isPopular: false,
  },
];

export const PRODUCTS_BY_GAME: Record<string, ProductSKU[]> = {
  "mobile-legends": calculateMLProductSKUs(5.5, 1.8),
  "free-fire": [
    {
      id: "ff-50",
      gameSlug: "free-fire",
      skuCode: "FF-50-DG",
      name: "50 Diamonds",
      itemAmount: "50 DM",
      basePrice: 6500,
      sellPrice: 7500,
      vipPrice: 6800,
      iconType: "diamond",
    },
    {
      id: "ff-70",
      gameSlug: "free-fire",
      skuCode: "FF-70-DG",
      name: "70 Diamonds",
      itemAmount: "70 DM",
      basePrice: 8900,
      sellPrice: 9900,
      vipPrice: 9200,
      isBestSeller: true,
      iconType: "diamond",
    },
    {
      id: "ff-140",
      gameSlug: "free-fire",
      skuCode: "FF-140-DG",
      name: "140 Diamonds",
      itemAmount: "140 DM",
      basePrice: 17800,
      sellPrice: 19500,
      vipPrice: 18300,
      isBestSeller: true,
      iconType: "diamond",
    },
    {
      id: "ff-355",
      gameSlug: "free-fire",
      skuCode: "FF-355-DG",
      name: "355 Diamonds",
      itemAmount: "355 DM",
      basePrice: 44500,
      sellPrice: 48900,
      vipPrice: 45900,
      iconType: "diamond",
    },
    {
      id: "ff-720",
      gameSlug: "free-fire",
      skuCode: "FF-720-DG",
      name: "720 Diamonds",
      itemAmount: "720 DM",
      basePrice: 89000,
      sellPrice: 97500,
      vipPrice: 91500,
      isPromo: true,
      iconType: "diamond",
    },
    {
      id: "ff-membership-weekly",
      gameSlug: "free-fire",
      skuCode: "FF-MBR-WEEKLY",
      name: "Member Mingguan",
      itemAmount: "Weekly",
      bonusAmount: "450 DM Total",
      basePrice: 28500,
      sellPrice: 31000,
      vipPrice: 29200,
      iconType: "pass",
    },
  ],
  "genshin-impact": [
    {
      id: "gi-welkin",
      gameSlug: "genshin-impact",
      skuCode: "GI-WELKIN",
      name: "Blessing of the Welkin Moon",
      itemAmount: "Welkin Moon",
      bonusAmount: "3000 Crystals Total",
      basePrice: 65000,
      sellPrice: 68500,
      vipPrice: 66200,
      isBestSeller: true,
      isPromo: true,
      iconType: "pass",
    },
    {
      id: "gi-60",
      gameSlug: "genshin-impact",
      skuCode: "GI-60",
      name: "60 Genesis Crystals",
      itemAmount: "60 Crystals",
      basePrice: 14500,
      sellPrice: 15900,
      vipPrice: 14900,
      iconType: "crystal",
    },
    {
      id: "gi-300",
      gameSlug: "genshin-impact",
      skuCode: "GI-300",
      name: "300+30 Genesis Crystals",
      itemAmount: "330 Crystals",
      basePrice: 72000,
      sellPrice: 77500,
      vipPrice: 73800,
      iconType: "crystal",
    },
    {
      id: "gi-980",
      gameSlug: "genshin-impact",
      skuCode: "GI-980",
      name: "980+110 Genesis Crystals",
      itemAmount: "1090 Crystals",
      basePrice: 228000,
      sellPrice: 242000,
      vipPrice: 232000,
      iconType: "crystal",
    },
  ],
  "pubg-mobile": [
    {
      id: "pubg-60",
      gameSlug: "pubg-mobile",
      skuCode: "PUBG-60",
      name: "60 Unknown Cash",
      itemAmount: "60 UC",
      basePrice: 13500,
      sellPrice: 14800,
      vipPrice: 13900,
      iconType: "uc",
    },
    {
      id: "pubg-325",
      gameSlug: "pubg-mobile",
      skuCode: "PUBG-325",
      name: "300+25 Unknown Cash",
      itemAmount: "325 UC",
      basePrice: 68000,
      sellPrice: 73500,
      vipPrice: 69500,
      isBestSeller: true,
      iconType: "uc",
    },
    {
      id: "pubg-660",
      gameSlug: "pubg-mobile",
      skuCode: "PUBG-660",
      name: "600+60 Unknown Cash",
      itemAmount: "660 UC",
      basePrice: 136000,
      sellPrice: 146000,
      vipPrice: 139000,
      iconType: "uc",
    },
  ],
  valorant: [
    {
      id: "val-475",
      gameSlug: "valorant",
      skuCode: "VAL-475",
      name: "475 Valorant Points",
      itemAmount: "475 VP",
      basePrice: 50000,
      sellPrice: 54000,
      vipPrice: 51200,
      iconType: "vp",
    },
    {
      id: "val-1000",
      gameSlug: "valorant",
      skuCode: "VAL-1000",
      name: "1000 Valorant Points",
      itemAmount: "1000 VP",
      basePrice: 100000,
      sellPrice: 107000,
      vipPrice: 102000,
      isBestSeller: true,
      iconType: "vp",
    },
  ],
};

export const PAYMENT_CHANNELS: PaymentChannel[] = [
  {
    id: "QRIS",
    name: "QRIS All Payment (GoPay, OVO, ShopeePay, BCA, Mandiri, Dana)",
    category: "QRIS",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e1/QRIS_logo.svg",
    feePercent: 0.7,
    feeFlat: 0,
    badge: "0% Biaya Admin — Paling Hemat",
    minAmount: 1000,
  },
  {
    id: "DANA",
    name: "DANA E-Wallet",
    category: "E_WALLET",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/72/Logo_dana_blue.svg",
    feePercent: 1.5,
    feeFlat: 0,
    badge: "Instan 3 Detik",
    minAmount: 5000,
  },
  {
    id: "SHOPEEPAY",
    name: "ShopeePay",
    category: "E_WALLET",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Shopee_logo.svg",
    feePercent: 1.5,
    feeFlat: 0,
    minAmount: 5000,
  },
  {
    id: "GOPAY",
    name: "GoPay",
    category: "E_WALLET",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/86/Gopay_logo.svg",
    feePercent: 1.5,
    feeFlat: 0,
    minAmount: 5000,
  },
  {
    id: "BCA_VA",
    name: "BCA Virtual Account",
    category: "VIRTUAL_ACCOUNT",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Bank_Central_Asia.svg",
    feePercent: 0,
    feeFlat: 2500,
    badge: "Otomatis 24 Jam",
    minAmount: 10000,
  },
  {
    id: "MANDIRI_VA",
    name: "Mandiri Virtual Account",
    category: "VIRTUAL_ACCOUNT",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Bank_Mandiri_logo_2016.svg",
    feePercent: 0,
    feeFlat: 2500,
    minAmount: 10000,
  },
  {
    id: "BRI_VA",
    name: "BRI Virtual Account (BRIVA)",
    category: "VIRTUAL_ACCOUNT",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/68/BANK_BRI_logo.svg",
    feePercent: 0,
    feeFlat: 2500,
    minAmount: 10000,
  },
  {
    id: "ALFAMART",
    name: "Alfamart / Alfamidi",
    category: "CONVENIENCE_STORE",
    logo: "https://upload.wikimedia.org/wikipedia/commons/8/86/Alfamart_logo.svg",
    feePercent: 0,
    feeFlat: 3500,
    badge: "Bayar di Kasir",
    minAmount: 15000,
  },
];

export const ACTIVE_VOUCHERS: VoucherCoupon[] = [];

export const EXCLUSIVE_STREAMER_PARTNER: ExclusivePartnerConfig = {
  partnerName: "Partner Streamer Resmi",
  channelName: "@StreamerGamingID",
  platform: "YouTube",
  referralCode: "STREAMER",
  discountValue: 2000,
  minSpend: 20000,
  profitSharePercent: 50, // 50% Streamer : 50% Owner Web
  tagline: "Official Gaming Top Up Store x Partner Streamer",
  streamUrl: "https://youtube.com",
};

export const STREAMER_REFERRALS: StreamerReferral[] = [
  {
    code: EXCLUSIVE_STREAMER_PARTNER.referralCode,
    streamerName: EXCLUSIVE_STREAMER_PARTNER.partnerName,
    platform: EXCLUSIVE_STREAMER_PARTNER.platform,
    discountType: "FIXED",
    discountValue: EXCLUSIVE_STREAMER_PARTNER.discountValue,
    minSpend: EXCLUSIVE_STREAMER_PARTNER.minSpend,
    description: `Kode Eksklusif Livestream: Potongan Rp ${EXCLUSIVE_STREAMER_PARTNER.discountValue.toLocaleString("id-ID")} langsung!`,
    streamerNote: `🎉 Terima kasih sudah berbelanja & support livestream ${EXCLUSIVE_STREAMER_PARTNER.partnerName}!`,
  },
];

export const INITIAL_SAVED_ACCOUNTS: SavedGameAccount[] = [
  {
    id: "save-1",
    gameSlug: "mobile-legends",
    gameName: "Mobile Legends",
    userId: "84920194",
    zoneId: "2172",
    nickname: "RRQ Lemonade (Saved)",
    lastUsed: "2 jam yang lalu",
  },
  {
    id: "save-2",
    gameSlug: "free-fire",
    gameName: "Free Fire",
    userId: "192837410",
    nickname: "EVOS_Sultan99",
    lastUsed: "Kemarin",
  },
];

export const LIVE_TRANSACTIONS_FEED = [
  { text: "0812****892 baru saja top up 86 Diamond MLBB", time: "3 detik lalu" },
  { text: "0857****119 baru saja beli WDP MLBB (Rp 28.900)", time: "12 detik lalu" },
  { text: "0896****401 baru saja top up 140 Diamond Free Fire", time: "28 detik lalu" },
  { text: "0821****345 baru saja beli Welkin Moon Genshin Impact", time: "45 detik lalu" },
  { text: "0878****981 baru saja top up 1000 VP Valorant", time: "1 menit lalu" },
];
